### PR TITLE
Connect bug #943

### LINKED ISSUE #943: REST::Connect needs a PushUpdate to realize a connection has been cancelled
This is an old bug that has been fixed in the gRPC implementation. REST, or at least Boost, does not seem to have a good way of detecting when the client has been disconnected. Further research needs to be done as to a solution.

### PR DESCRIPTION
**Pull request by nelgd**
Closes issue #943 

Gave fixing this bug a shot based off what was done for the gRPC fix

Added a new unit test to check for the disconnect update and all other unit tests still pass

### CODE REVIEW

File: sdks/cpp/connections/REST/src/ServiceImpl.cpp [hunk 1]
```diff
@@ -19,6 +19,13 @@ using catena::REST::ServiceImpl;
 
 using catena::REST::Connect;
 
+#if !defined(_WIN32)
```
Comment (abrown-RV) [inline sdks/cpp/connections/REST/src/ServiceImpl.cpp]: we don't support windows, so I think just take out WIN32 gates

**Review by abrown-RV — CHANGES_REQUESTED** [review]
If I'm understanding correctly, this will change the sendResponse to gracefully close the connection if it tries to send and the other side has hung up. And then sets up a heartbeat to wake up and send on an interval so that the failure occurs and then gracefully shuts down the connection.

So we already have a heartbeat, so I think the resolution here is to keep the graceful shutdown part and then just use the existing heartbeat. Your unit test for this would just be to send a regular param update where the client has hung up, and check that it gracefully closes.

**Comment by nelgd** [comment]
> If I'm understanding correctly, this will change the sendResponse to gracefully close the connection if it tries to send and the other side has hung up. And then sets up a heartbeat to wake up and send on an interval so that the failure occurs and then gracefully shuts down the connection.
> 
> So we already have a heartbeat, so I think the resolution here is to keep the graceful shutdown part and then just use the existing heartbeat. Your unit test for this would just be to send a regular param update where the client has hung up, and check that it gracefully closes.

Got all that done. I had an issue where coverage was passing locally but not on the repo. 

Would you be able to explain what this code that Chat got me to add to `ServiceImpl.cpp` does to fix the problem?

```
// Open and bind the acceptor with reuse_address to reduce flakiness on CI
    boost::system::error_code ec;
    acceptor_.open(tcp::v4(), ec);
    if (ec) {
        throw std::runtime_error(std::string("Failed to open acceptor: ") + ec.message());
    }
    acceptor_.set_option(boost::asio::socket_base::reuse_address(true), ec);
    // Ignore ec from set_option; continue to bind
    acceptor_.bind(tcp::endpoint(tcp::v4(), config.port), ec);
    if (ec) {
        throw std::runtime_error(std::string("Failed to bind port ") + std::to_string(config.port) + ": " + ec.message());
    }
    acceptor_.listen(boost::asio::socket_base::max_listen_connections, ec);
    if (ec) {
        throw std::runtime_error(std::string("Failed to listen on port ") + std::to_string(config.port) + ": " + ec.message());
    }
 ```

File: sdks/cpp/connections/REST/src/ServiceImpl.cpp [hunk 2]
```diff
@@ -90,6 +112,18 @@ void ServiceImpl::run() {
...
+            socket.set_option(boost::asio::socket_base::keep_alive(true));
+            int yes = 1;
+            int idle = 30;     // seconds before sending keepalive probes
+            int intvl = 10;    // interval between keepalive probes
+            int cnt = 3;       // probes before declaring dead
+            ::setsockopt(socket.native_handle(), SOL_SOCKET, SO_KEEPALIVE, &yes, sizeof(yes));
+            ::setsockopt(socket.native_handle(), IPPROTO_TCP, TCP_KEEPIDLE, &idle, sizeof(idle));
+            ::setsockopt(socket.native_handle(), IPPROTO_TCP, TCP_KEEPINTVL, &intvl, sizeof(intvl));
+            ::setsockopt(socket.native_handle(), IPPROTO_TCP, TCP_KEEPCNT, &cnt, sizeof(cnt));
+        } catch (...) { /* best-effort keepalive */ }
```
Comment (abrown-RV) [inline sdks/cpp/connections/REST/src/ServiceImpl.cpp]: Gonna say take all this out as well. We don't need multiple keepalives, and I misspoke, gRPC does not have a transport level keepalive either. It also has the ability, we've just elected to use our application level keepalive.

File: sdks/cpp/connections/REST/src/SocketWriter.cpp [hunk 3]
```diff
@@ -48,7 +48,12 @@ void SocketWriter::sendResponse(const catena::exception_with_status& err, const
                  << "Access-Control-Allow-Headers: Content-Type, Authorization, accept, Origin, X-Requested-With, Language, Detail-Level\r\n"
                  << "Access-Control-Allow-Credentials: true\r\n\r\n"
                  << jsonBody_;
-        boost::asio::write(socket_, boost::asio::buffer(response.str()));
+        // Use non-throwing write; on error, close socket to signal disconnect
+        boost::system::error_code ec;
+        boost::asio::write(socket_, boost::asio::buffer(response.str()), ec);
+        if (ec) {
+            socket_.close();
```
Comment (abrown-RV) [inline sdks/cpp/connections/REST/src/SocketWriter.cpp:57]: log the error at warning level: `LOG(WARNING) << message`

File: sdks/cpp/connections/REST/src/SocketWriter.cpp [hunk 4]
```diff
@@ -85,10 +90,15 @@ void SSEWriter::sendResponse(const catena::exception_with_status& err, const goo
...
     if (httpStatus.first < 300 && !jsonOutput.empty()) {
         response << "data: " << jsonOutput << "\n\n";
     }
 
-    boost::asio::write(socket_, boost::asio::buffer(response.str()));
+    // Use non-throwing write; on error, close socket to signal disconnect
+    boost::system::error_code ec;
+    boost::asio::write(socket_, boost::asio::buffer(response.str()), ec);
+    if (ec) {
+        socket_.close();
```
Comment (abrown-RV) [inline sdks/cpp/connections/REST/src/SocketWriter.cpp:105]: same, log it please

**Review by abrown-RV — CHANGES_REQUESTED** [review]
I'd also like to see a unit test (if possible) that connects sends a message, disconnects the client, and then send another message that should trigger the graceful shutdown.

Nice work!

File: sdks/cpp/connections/REST/src/ServiceImpl.cpp [hunk 5]
```diff
@@ -19,6 +19,11 @@ using catena::REST::ServiceImpl;
 
 using catena::REST::Connect;
 
+#include <sys/types.h>
+#include <sys/socket.h>
+#include <netinet/tcp.h>
+#include <netinet/in.h>
+
```
Comment (abrown-RV) [inline sdks/cpp/connections/REST/src/ServiceImpl.cpp]: I think these are also no longer necessary without all the `setopts`?

File: sdks/cpp/connections/REST/src/ServiceImpl.cpp [hunk 6]
```diff
@@ -90,7 +95,7 @@ void ServiceImpl::run() {
         // Waiting for a connection.
         tcp::socket socket(io_context_);
         acceptor_.accept(socket);
-        // Once a connection is made, increment activeRequests and handle async.
+
```
Comment (abrown-RV) [inline sdks/cpp/connections/REST/src/ServiceImpl.cpp]:
```suggestion
        // Once a connection is made, increment activeRequests and handle async.
```

File: sdks/cpp/connections/REST/src/SocketWriter.cpp [hunk 7]
```diff
@@ -1,4 +1,5 @@
 #include <SocketWriter.h>
+#include <absl/log/log.h>
```
Comment (abrown-RV) [inline sdks/cpp/connections/REST/src/SocketWriter.cpp]: We actually have a `Logger.h` that abstracts absl that you should include instead.

File: unittests/cpp/REST/tests/ServiceImpl_test.cpp [hunk 8]
```diff
@@ -53,6 +53,12 @@
 using namespace catena::common;
 using namespace catena::REST;
 
+#include <atomic>
+
+namespace {
+    std::atomic<uint16_t> s_next_port{50050};
```
Comment (abrown-RV) [inline unittests/cpp/REST/tests/ServiceImpl_test.cpp]: Just make this a field on the `RESTServiceImplTests` class

File: unittests/cpp/REST/tests/SocketWriter_test.cpp [hunk 9]
```diff
@@ -310,3 +309,41 @@ TEST_F(RESTSocketWriterTests, SSEWriter_WriteErrEnd) {
...
+    google::protobuf::util::JsonPrintOptions options;
+    auto status = google::protobuf::util::MessageToJsonString(msg1, &jsonBody1, options);
+    EXPECT_EQ(readResponse(), expectedResponse(rc, jsonBody1));
+
+    // Shutdown and close client socket to simulate unexpected client disconnect.
+    boost::system::error_code ec;
+    clientSocket_.shutdown(tcp::socket::shutdown_both, ec);
+    clientSocket_.close();
+
+    // Writing multiple messages to ensure the error is triggered.
```
Comment (abrown-RV) [inline unittests/cpp/REST/tests/SocketWriter_test.cpp]: Why multiple? shouldn't it just always die right away? Or is there some delay after calling `clientSocket_.close()` before it actually closes?

**Review by abrown-RV — CHANGES_REQUESTED** [review]
Very nice Nelson, just a little bit of cleanup, and a question.

File: sdks/cpp/connections/REST/src/ServiceImpl.cpp (hunk 5 above)
Comment (nelgd) [reply sdks/cpp/connections/REST/src/ServiceImpl.cpp]: Yeah I thought so also. I removed them and then the build failed on github so I reverted it

Comment (abrown-RV) [reply sdks/cpp/connections/REST/src/ServiceImpl.cpp]: built fine for me locally, if it's failing on github, that's an issue worth investigating

Comment (nelgd) [reply sdks/cpp/connections/REST/src/ServiceImpl.cpp]: ill give it another shot and see what happens

File: unittests/cpp/REST/tests/SocketWriter_test.cpp (hunk 9 above)
Comment (nelgd) [reply unittests/cpp/REST/tests/SocketWriter_test.cpp]: Yeah, multiple is unneeded. Changed it just to one

Comment (nelgd) [reply unittests/cpp/REST/tests/SocketWriter_test.cpp]: Had issues with just one. I asked chat to explain why multiple might be needed. Is this valid reasoning?
image

File: sdks/cpp/connections/REST/src/ServiceImpl.cpp (hunk 6 above)
Comment (abrown-RV) [reply sdks/cpp/connections/REST/src/ServiceImpl.cpp]: I think this comment is still valid, especially since there's no other changes in the file now.

File: unittests/cpp/REST/tests/ServiceImpl_test.cpp
Comment (abrown-RV) [inline unittests/cpp/REST/tests/ServiceImpl_test.cpp:1]: Add yourself to `@author` here too

**Review by abrown-RV — CHANGES_REQUESTED** [review]
Lookin good just a couple little fixes

File: unittests/cpp/REST/tests/ServiceImpl_test.cpp
Comment (nelgd) [reply unittests/cpp/REST/tests/ServiceImpl_test.cpp:1]: Added myself and added back the comment

**Review by abrown-RV — APPROVED** [review]
nice work! 👍
