### PR TITLE
Fixed ParamInfo Unary response behaviour

### LINKED ISSUE #1288: [C++] ParamInfo REST incorrect response
## 📖 Description

The `/{slot}/param-info/{fqoid}` endpoint currently returns incorrect json:
```json
{
    "data": [
        {
            "info": {
                "oid": "counter",
                "name": {
                    "displayStrings": {
                        "en": "Counter"
                    }
                },
                "type": "INT32"
            }
        }
    ]
}
```
according to openapi.yaml it shouldn't have that outer `data` wrapper:
```yaml
  param_info_response:
    title: Param Info Response
    description: |
      Information about a parameter - it's id and descriptor.
    type: object
    properties:
      info:
        $ref: "#/$defs/param_info"
      array_length:
        $ref: "#/$defs/total_length"
    required:
      - info
    additionalProperties: false
```

---

## 🎯 Goal / Outcome

Correct response from the endpoint

---

## ✅ Definition of Done (DoD)
- [ ] Feature is implemented and works as expected
- [ ] Edge cases are handled
- [ ] Tests are added or updated (if applicable)
- [ ] Documentation is updated (if needed)
- [ ] Code is reviewed and approved

---

## 🛠️ Implementation Notes (Optional)

---

## 🔗 Related Issues / Links

---
## 🚧 Risks / Open Questions (Optional)

---

### PR DESCRIPTION
**Pull request by KeonF-ross**
## 📖 Description

Fixed bug and unintended behavior of ParamInfoRequest with a Unary response. The code would allow for a Mode 1 (no fqoid/GetAllTopLevelParams) Unary response although the `openapi.yaml` doesn't specify it as a supported endpoint. There was also a bug that caused the correctly supported Mode 3 (specified fqoid) to have a `data` wrapper when that is not specified by the `openapi.yaml`.

---

## ✅ Definition of Done (DoD)

- [x] Unary response only support mode 3
- [x] Unary response no longer has data wrapper

---

## 🛠️ Implementation Notes

- Modified `ParamInfoRequest.cpp`
    - `SocketWriter` no longer set up to use buffering
    - Now throws error if  Unary and no fqoid
    - Only calls `sendResponse()` once if Unary
- Modified `ParamInfoRequestTest.cpp`
    - Removed test for Mode 1 with Unary response

---

## 🔗 Related Issues / Links

[Issue #1288](https://github.com/rossvideo/Catena/issues/1288?reload=1?reload=1)

---
## 📝 Additional Context

Could discuss as a team if we want to go through with these changes of enforcing Unary to be only Mode 3, or if we instead want to update the `openapi.yaml` with support for Unary on Mode 1.

---

## 🚧 Risks / Open Questions

---
## ✨ Updates
<!-- (Optional) List summarizing changes made when editing the pull request>

### CODE REVIEW

File: unittests/cpp/REST/tests/ParamInfoRequest_test.cpp [hunk 1]
```diff
@@ -278,48 +278,6 @@ TEST_F(RESTParamInfoRequestTests, ParamInfoRequest_getTopLevelParamsStream) {
     EXPECT_EQ(readResponse(), expectedSSEResponse(expRc_, jsonBodies));
 }
 
-// Test 1.2: Get all top-level parameters without recursion as a unary response.
-TEST_F(RESTParamInfoRequestTests, ParamInfoRequest_getTopLevelParamsUnary) {
```
Comment (abrown-RV) [inline unittests/cpp/REST/tests/ParamInfoRequest_test.cpp:282]: convert this into a EXPECT_FAIL test instead of removing

**Review by abrown-RV — CHANGES_REQUESTED** [review]
bit of an fail on the part of our unit test design if you didn't actually need to change them to make them pass with a different response.... oh well!

**Comment by KeonF-ross** [comment]
bugbot run

**Review by abrown-RV — APPROVED** [review]
